---
apiVersion: v1
kind: Service
metadata:
  name: results 
  labels: 
    role: results
spec:
  selector:
    role: results
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30400
